// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TC32HinthbocodoanhthutheothngTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tC32Hinthbocodoanhthutheothng() {
    driver.Navigate().GoToUrl("http://nupakachi.somee.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(784, 816);
    driver.FindElement(By.LinkText("Quản Trị")).Click();
    driver.FindElement(By.LinkText("Báo cáo")).Click();
    driver.FindElement(By.Name("tuNgay")).Click();
    driver.FindElement(By.Name("tuNgay")).SendKeys("2026-02-10");
    driver.FindElement(By.CssSelector(".row:nth-child(4)")).Click();
    driver.FindElement(By.CssSelector(".btn-pink")).Click();
    driver.Close();
  }
}
