// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TC31MoTrangGioHangTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tC31MoTrangGioHang() {
    driver.Navigate().GoToUrl("http://nupakachi.somee.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1232, 1079);
    driver.FindElement(By.LinkText("🛍")).Click();
    try {
      Thread.Sleep(2000);
    } catch {
      Console.WriteLine("{0} Exception caught.", e);
    }
    Assert.That(driver.FindElement(By.CssSelector(".text-pink")).Text, Is.EqualTo("Giỏ hàng của bạn đang trống!"));
    driver.FindElement(By.CssSelector("strong")).Click();
    driver.FindElement(By.CssSelector(".empty-cart-area")).Click();
    driver.Close();
  }
}
