// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TC34ThemTuTimKiemTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tC34ThemTuTimKiem() {
    driver.Navigate().GoToUrl("http://nupakachi.somee.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1232, 1079);
    driver.FindElement(By.Name("search")).Click();
    driver.FindElement(By.Name("search")).SendKeys("Áo");
    driver.FindElement(By.Name("search")).SendKeys(Keys.Enter);
    try {
      Thread.Sleep(2000);
    } catch {
      Console.WriteLine("{0} Exception caught.", e);
    }
    driver.FindElement(By.CssSelector(".col-lg-4:nth-child(3) .btn-pink-outline")).Click();
    driver.FindElement(By.CssSelector(".btn-pink")).Click();
    try {
      Thread.Sleep(2000);
    } catch {
      Console.WriteLine("{0} Exception caught.", e);
    }
    driver.FindElement(By.CssSelector(".card:nth-child(2) .card-title")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".card:nth-child(2) .card-title")).Text, Is.EqualTo("Áo Khoác Da Nam Dáng Bomber Đen"));
    driver.FindElement(By.CssSelector(".col-md-4:nth-child(2)")).Click();
    driver.Close();
  }
}
