// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TC49GiaoDienTabletTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tC49GiaoDienTablet() {
    driver.Navigate().GoToUrl("http://nupakachi.somee.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1289, 1079);
    driver.FindElement(By.CssSelector(".justify-content-between")).Click();
    driver.FindElement(By.CssSelector(".py-5:nth-child(6)")).Click();
    driver.FindElement(By.CssSelector(".py-5:nth-child(6) .col-lg-3:nth-child(3) .btn-pink-outline")).Click();
    try {
      Thread.Sleep(2000);
    } catch {
      Console.WriteLine("{0} Exception caught.", e);
    }
    driver.FindElement(By.CssSelector(".row:nth-child(4)")).Click();
    driver.Close();
  }
}
