// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TC50GiaoDienDesktopTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tC50GiaoDienDesktop() {
    driver.Navigate().GoToUrl("http://nupakachi.somee.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1687, 1093);
    driver.FindElement(By.CssSelector(".py-5:nth-child(5)")).Click();
    driver.FindElement(By.CssSelector(".hero-overlay")).Click();
    driver.FindElement(By.LinkText("Sản phẩm")).Click();
    try {
      Thread.Sleep(2000);
    } catch {
      Console.WriteLine("{0} Exception caught.", e);
    }
    driver.FindElement(By.LinkText("2")).Click();
    driver.Close();
  }
}
